# 区分多个instance的VRRP组播，同网段不能重复，取值在0-255之间
# 可以直接指定数字，如ROUTER_ID: 111 
# 取100~200间的随机数
#ROUTER_ID: "{{ 200 | random }}"
ROUTER_ID: 111

# haproxy负载均衡算法，常见如下：
# "roundrobin": 基于服务器权重的轮询
# "leastconn": 基于服务器最小连接数
# "source": 基于请求源IP地址
# "uri": 基于请求的URI
BALANCE_ALG: "roundrobin"
