// AUTH
export const ACCOUNT_AUTH_STATUS_CHANGED = 'ACCOUNT_AUTH_STATUS_CHANGED';
// Login
export const ACCOUNT_LOGIN_INIT = 'ACCOUNT_LOGIN_INIT';
export const ACCOUNT_LOGIN_SUBMIT_SUCCESS = 'ACCOUNT_LOGIN_SUBMIT_SUCCESS';
export const ACCOUNT_LOGIN_SUBMIT_FAILURE = 'ACCOUNT_LOGIN_SUBMIT_FAILURE';
// Logout
export const ACCOUNT_LOGOUT_INIT = 'ACCOUNT_LOGOUT_INIT';
export const ACCOUNT_LOGOUT_SUBMIT_SUCCESS = 'ACCOUNT_LOGOUT_SUBMIT_SUCCESS';
export const ACCOUNT_LOGOUT_SUBMIT_FAILURE = 'ACCOUNT_LOGOUT_SUBMIT_FAILURE';

//SEARCH_CUSTOMER
export const SEARCH_CUSTOMER_GET_LISTS_SUCCESS = 'SEARCH_CUSTOMER_GET_LISTS_SUCCESS';
export const VIEW_CUSTOMER_GET_SUCESS = 'VIEW_CUSTOMER_GET_SUCESS';
export const VIEW_CUSTOMER_GET_FAILURE = 'VIEW_CUSTOMER_GET_FAILURE';

//SELECT_CUSTOMER
export const SELECT_CUSTOMER ='SELECT_CUSTOMER';

export const ACCOUNT_SELECTED_CHANGED ='ACCOUNT_SELECTED_CHANGED';

export const ACCOUNT_WAITPAY_CHANGED ='ACCOUNT_WAITPAY_CHANGED';

